version: 2.1
jobs:
  trial:
    docker:
      - image: circleci/ruby:2.5.3
    parallelism: 3
    steps:
      - run: lscpu
      - run: ./pnd.sh

workflows:
  version: 2.1
  build:
    jobs:
      - trial
